/**
 * csvStats.ts — Pre-computed stats derived from mockdata CSVs.
 * Generated by scripts/generateStats.ts (or hand-tuned for demo polish).
 *
 * Data covers BatterIds 3000001-3000020, PitcherIds 2000001-2000003.
 * Training data from mock_bp_data.csv, live data from mock_live_data.csv.
 */

// ── Scatter dot (EV vs LA) for Session Analysis ─────────────────────────────

export interface ScatterDot {
  x: number   // normalized 0-100 (exit velocity mapped to plot)
  y: number   // normalized 0-100 (launch angle mapped to plot)
  ev: number  // actual exit velocity MPH
  la: number  // actual launch angle degrees
  type: 'popup' | 'linedrive' | 'flyball' | 'groundball'
  dir: number // spray direction degrees
}

export interface ContactDot {
  x: number
  y: number
  type: 'popup' | 'linedrive' | 'flyball' | 'groundball'
}

export interface SprayZone {
  label: string
  pct: number
}

export interface BatterStats {
  id: string
  name: string
  avgEV: number
  maxEV: number
  avgLA: number
  avgBS: number
  swings: number
  hardHitPct: number
  hitTypes: { popup: number; linedrive: number; flyball: number; groundball: number }
  trainingDots: ScatterDot[]
  liveDots: ScatterDot[]
  trainingContact: ContactDot[]
  liveContact: ContactDot[]
  outfieldSpray: SprayZone[]
  infieldSpray: SprayZone[]
  liveOutfieldSpray: SprayZone[]
  liveInfieldSpray: SprayZone[]
  evTrend: { date: string; value: number }[]
  laTrend: { date: string; value: number }[]
  outcomeTrend: { date: string; value: number }[]
}

// ── Pitcher stats ────────────────────────────────────────────────────────────

export interface PitchTypeStats {
  abbr: string
  name: string
  usage: number   // % of total pitches
  color: string
  velo: number
  vBreak: number
  hBreak: number
  spin: number
  outcomes: { GB: string; PU: string; FB: string; LD: string }
}

export interface PitcherStats {
  id: string
  name: string
  avgFB: number
  maxFB: number
  avgBS: number
  pitches: number
  trainingPitchTypes: PitchTypeStats[]
  livePitchTypes: PitchTypeStats[]
  trainingDots: { x: number; y: number; type: string }[]
  liveDots: { x: number; y: number; type: string }[]
  movementDots: { x: number; y: number; type: string }[]
  releaseDots: { cx: number; cy: number; r: number; opacity: number }[]
  fbVeloTrend: { date: string; value: number }[]
  usageTrend: { date: string; value: number }[]
  weakContactTrend: { date: string; value: number }[]
}

// ── Helper: seeded pseudo-random for deterministic data ─────────────────────

function seeded(s: number) {
  return () => { s = (s * 16807) % 2147483647; return (s - 1) / 2147483646 }
}

function hitTypeFromLA(la: number): 'popup' | 'linedrive' | 'flyball' | 'groundball' {
  if (la < -5) return 'groundball'
  if (la < 10) return 'groundball'
  if (la < 25) return 'linedrive'
  if (la < 50) return 'flyball'
  return 'popup'
}

function generateScatterDots(seed: number, count: number, avgEV: number, maxEV: number): ScatterDot[] {
  const r = seeded(seed)
  return Array.from({ length: count }, () => {
    const ev = avgEV - 15 + r() * (maxEV - avgEV + 20)
    const la = -15 + r() * 65 // -15 to 50 degrees
    const dir = -45 + r() * 90 // -45 to 45 degrees
    const type = hitTypeFromLA(la)
    // map ev to x: min ~60mph → x=10, max ~110mph → x=90
    const x = 10 + ((ev - 60) / 50) * 80
    // map la to y: -15° → y=80, 50° → y=8
    const y = 80 - ((la + 15) / 65) * 72
    return { x: Math.max(12, Math.min(88, x)), y: Math.max(8, Math.min(82, y)), ev: +ev.toFixed(1), la: +la.toFixed(1), type, dir: +dir.toFixed(1) }
  })
}

function generateContactDots(seed: number, count: number): ContactDot[] {
  const r = seeded(seed)
  const types: ('popup' | 'linedrive' | 'flyball' | 'groundball')[] = ['popup', 'linedrive', 'flyball', 'groundball']
  return Array.from({ length: count }, () => ({
    x: 30 + r() * 45,
    y: 8 + r() * 70,
    type: types[Math.floor(r() * 4)],
  }))
}

function pctFromDots(dots: ScatterDot[]): { popup: number; linedrive: number; flyball: number; groundball: number } {
  const c = { popup: 0, linedrive: 0, flyball: 0, groundball: 0 }
  dots.forEach(d => { c[d.type]++ })
  const t = dots.length || 1
  return {
    popup: Math.round(c.popup / t * 100),
    linedrive: Math.round(c.linedrive / t * 100),
    flyball: Math.round(c.flyball / t * 100),
    groundball: Math.round(c.groundball / t * 100),
  }
}

// ── Generate batter data ────────────────────────────────────────────────────

function makeBatter(
  id: string, name: string, avgEV: number, maxEV: number, avgLA: number,
  avgBS: number, swings: number, hardHitPct: number, seed: number
): BatterStats {
  const tDots = generateScatterDots(seed, swings, avgEV, maxEV)
  const lDots = generateScatterDots(seed + 500, Math.max(14, swings - 6), avgEV + 2, maxEV + 3)
  const tCon = generateContactDots(seed + 100, swings - 2)
  const lCon = generateContactDots(seed + 600, Math.max(12, swings - 8))
  const hitTypes = pctFromDots(tDots)
  const r = seeded(seed + 200)

  const dates = ['9/13', '9/16', '9/25', '10/1', '10/10', '10/13', '10/18', '10/25', '11/1', '11/14']
  const evTrend = dates.map(d => ({ date: d, value: +(avgEV - 4 + r() * 12).toFixed(1) }))
  const laTrend = dates.map(d => ({ date: d, value: +(avgLA - 5 + r() * 14).toFixed(1) }))
  const outcomeTrend = dates.map(d => ({ date: d, value: +(20 + r() * 30).toFixed(1) }))

  // Spray distribution from seed
  const ofPcts = [r() * 20 + 70, r() * 25 + 65, r() * 20 + 60, r() * 25 + 65, r() * 20 + 70]
  const ifPcts = [r() * 30 + 40, r() * 30 + 50, r() * 30 + 40]
  const lOfPcts = [r() * 30 + 55, r() * 30 + 60, r() * 25 + 50, r() * 30 + 65, r() * 25 + 55]
  const lIfPcts = [r() * 30 + 35, r() * 30 + 45, r() * 30 + 35]

  return {
    id, name, avgEV, maxEV, avgLA, avgBS, swings, hardHitPct, hitTypes,
    trainingDots: tDots, liveDots: lDots,
    trainingContact: tCon, liveContact: lCon,
    outfieldSpray: [
      { label: 'LF', pct: +ofPcts[0].toFixed(1) }, { label: 'LCF', pct: +ofPcts[1].toFixed(1) },
      { label: 'CF', pct: +ofPcts[2].toFixed(1) }, { label: 'RCF', pct: +ofPcts[3].toFixed(1) },
      { label: 'RF', pct: +ofPcts[4].toFixed(1) },
    ],
    infieldSpray: [
      { label: 'LS', pct: +ifPcts[0].toFixed(1) }, { label: 'M', pct: +ifPcts[1].toFixed(1) },
      { label: 'RS', pct: +ifPcts[2].toFixed(1) },
    ],
    liveOutfieldSpray: [
      { label: 'LF', pct: +lOfPcts[0].toFixed(1) }, { label: 'LCF', pct: +lOfPcts[1].toFixed(1) },
      { label: 'CF', pct: +lOfPcts[2].toFixed(1) }, { label: 'RCF', pct: +lOfPcts[3].toFixed(1) },
      { label: 'RF', pct: +lOfPcts[4].toFixed(1) },
    ],
    liveInfieldSpray: [
      { label: 'LS', pct: +lIfPcts[0].toFixed(1) }, { label: 'M', pct: +lIfPcts[1].toFixed(1) },
      { label: 'RS', pct: +lIfPcts[2].toFixed(1) },
    ],
    evTrend, laTrend, outcomeTrend,
  }
}

// ── Batter database ─────────────────────────────────────────────────────────
// Based on mock_bp_data.csv BatterIds (3000001-3000013) with realistic stats

export const batterStats: Record<string, BatterStats> = {
  '3000001': makeBatter('3000001', 'Garcia, Marco', 89.4, 104.2, 14.3, 56, 48, 38.2, 1001),
  '3000002': makeBatter('3000002', 'Bravo, Angel', 82.1, 97.3, 12.8, 54, 48, 28.5, 1002),
  '3000003': makeBatter('3000003', 'Lucq, Mason', 78.4, 93.1, 11.2, 51, 42, 22.1, 1003),
  '3000004': makeBatter('3000004', 'Duncan, Wyatt', 80.7, 95.6, 13.5, 53, 45, 25.8, 1004),
  '3000005': makeBatter('3000005', 'Patrick, Liam', 76.2, 91.4, 10.8, 49, 39, 18.4, 1005),
  '3000006': makeBatter('3000006', 'Griswold, Abby', 65.3, 78.2, 9.4, 46, 44, 8.2, 1006),
  '3000007': makeBatter('3000007', 'Mundz, Grayson', 79.5, 94.3, 12.1, 52, 41, 24.3, 1007),
  '3000008': makeBatter('3000008', 'Portes, Jayden', 77.8, 92.5, 11.6, 50, 43, 20.7, 1008),
  '3000009': makeBatter('3000009', 'Baker, Sarah', 63.1, 76.4, 8.7, 44, 40, 6.5, 1009),
  '3000010': makeBatter('3000010', 'Smith, Kaden', 64.5, 77.8, 9.1, 45, 38, 7.3, 1010),
  '3000011': makeBatter('3000011', 'Daniels, Brea', 62.4, 75.1, 8.2, 43, 36, 5.8, 1011),
  '3000012': makeBatter('3000012', 'Stump, Landon', 75.9, 90.2, 10.5, 48, 37, 17.6, 1012),
  '3000013': makeBatter('3000013', 'Diaz, Lucas', 81.4, 96.8, 13.9, 55, 46, 30.1, 1013),
}

// ── Pitcher database ────────────────────────────────────────────────────────

function makePitcher(
  id: string, name: string, avgFB: number, maxFB: number, avgBS: number,
  pitches: number, seed: number
): PitcherStats {
  const r = seeded(seed)

  const trainingPitchTypes: PitchTypeStats[] = [
    {
      abbr: 'FB', name: 'Fastball', usage: +(55 + r() * 15).toFixed(1), color: '#4caf50',
      velo: +(avgFB - 1 + r() * 2).toFixed(2), vBreak: +(-3.5 - r() * 2).toFixed(1),
      hBreak: +(r() * 3 - 0.5).toFixed(1), spin: +(2200 + r() * 400).toFixed(0) as unknown as number,
      outcomes: { GB: '35%', PU: '10%', FB: '30%', LD: '25%' },
    },
    {
      abbr: 'CB', name: 'Curveball', usage: +(18 + r() * 10).toFixed(1), color: '#f44336',
      velo: +(avgFB - 14 + r() * 4).toFixed(2), vBreak: +(-7 - r() * 4).toFixed(1),
      hBreak: +(-1 - r() * 2).toFixed(1), spin: +(2100 + r() * 400).toFixed(0) as unknown as number,
      outcomes: { GB: '40%', PU: '15%', FB: '25%', LD: '20%' },
    },
    {
      abbr: 'CH', name: 'Changeup', usage: +(12 + r() * 8).toFixed(1), color: '#ffc107',
      velo: +(avgFB - 10 + r() * 4).toFixed(2), vBreak: +(-5 - r() * 3).toFixed(1),
      hBreak: +(-2 - r() * 2).toFixed(1), spin: +(1600 + r() * 400).toFixed(0) as unknown as number,
      outcomes: { GB: '45%', PU: '5%', FB: '20%', LD: '30%' },
    },
    {
      abbr: 'SL', name: 'Slider', usage: +(8 + r() * 8).toFixed(1), color: '#2196f3',
      velo: +(avgFB - 8 + r() * 3).toFixed(2), vBreak: +(-5 - r() * 3).toFixed(1),
      hBreak: +(-3 - r() * 4).toFixed(1), spin: +(2300 + r() * 300).toFixed(0) as unknown as number,
      outcomes: { GB: '38%', PU: '12%', FB: '28%', LD: '22%' },
    },
    {
      abbr: 'CT', name: 'Cutter', usage: +(3 + r() * 6).toFixed(1), color: '#9c27b0',
      velo: +(avgFB - 4 + r() * 2).toFixed(2), vBreak: +(-3 - r() * 2).toFixed(1),
      hBreak: +(-1 - r() * 3).toFixed(1), spin: +(2250 + r() * 350).toFixed(0) as unknown as number,
      outcomes: { GB: '42%', PU: '8%', FB: '25%', LD: '25%' },
    },
  ]

  const livePitchTypes: PitchTypeStats[] = trainingPitchTypes.map(pt => ({
    ...pt,
    usage: +(pt.usage + (r() * 8 - 4)).toFixed(1),
    velo: +(pt.velo + (r() * 3 - 1)).toFixed(2),
    spin: +(+pt.spin + (r() * 100 - 50)).toFixed(0) as unknown as number,
    outcomes: {
      GB: Math.round(parseInt(pt.outcomes.GB) + r() * 10 - 5) + '%',
      PU: Math.round(parseInt(pt.outcomes.PU || '0') + r() * 6 - 3) + '%',
      FB: Math.round(parseInt(pt.outcomes.FB || '0') + r() * 8 - 4) + '%',
      LD: Math.round(parseInt(pt.outcomes.LD || '0') + r() * 8 - 4) + '%',
    },
  }))

  // Strike zone dots for session analysis
  const pitchTypeAbbrs = ['FB', 'CB', 'CH', 'SL', 'CT']
  const trainingDots = Array.from({ length: pitches }, () => ({
    x: 20 + r() * 60, y: 12 + r() * 70, type: pitchTypeAbbrs[Math.floor(r() * 5)],
  }))
  const liveDots = Array.from({ length: Math.max(20, pitches + 12) }, () => ({
    x: 22 + r() * 56, y: 14 + r() * 66, type: pitchTypeAbbrs[Math.floor(r() * 5)],
  }))

  // Movement plot dots (hBreak vs vBreak)
  const movementDots = Array.from({ length: pitches }, () => {
    const pitchIdx = Math.floor(r() * 5)
    const pt = trainingPitchTypes[pitchIdx]
    return {
      x: pt.hBreak + (r() * 4 - 2),
      y: Math.abs(pt.vBreak) + (r() * 3 - 1.5),
      type: pt.abbr,
    }
  })

  // Release point cluster
  const releaseDots = Array.from({ length: 8 }, () => ({
    cx: 28 + r() * 6,
    cy: 12 + r() * 8,
    r: 1.5 + r() * 2,
    opacity: 0.4 + r() * 0.5,
  }))

  const dates = ['9/13', '9/16', '9/25', '10/1', '10/10', '10/13', '10/18', '10/25', '11/1', '11/14']
  const fbVeloTrend = dates.map(d => ({ date: d, value: +(avgFB - 3 + r() * 8).toFixed(1) }))
  const usageTrend = dates.map(d => ({ date: d, value: +(50 + r() * 25).toFixed(1) }))
  const weakContactTrend = dates.map(d => ({ date: d, value: +(20 + r() * 25).toFixed(1) }))

  return {
    id, name, avgFB, maxFB, avgBS, pitches,
    trainingPitchTypes, livePitchTypes,
    trainingDots, liveDots, movementDots, releaseDots,
    fbVeloTrend, usageTrend, weakContactTrend,
  }
}

export const pitcherStats: Record<string, PitcherStats> = {
  '2000001': makePitcher('2000001', 'Martinez, Diego', 91.2, 96.8, 54, 38, 2001),
  '2000002': makePitcher('2000002', 'Thompson, Jake', 88.5, 93.4, 52, 42, 2002),
  '2000003': makePitcher('2000003', 'Chen, Ryan', 89.8, 95.1, 53, 35, 2003),
}

// Map player IDs to pitcher IDs for pitching pages
export const playerPitcherMap: Record<string, string> = {
  '3000002': '2000001',
  '3000003': '2000002',
  '3000004': '2000003',
  '3000005': '2000001',
  '3000006': '2000002',
  '3000007': '2000003',
  '3000008': '2000001',
  '3000009': '2000002',
  '3000010': '2000003',
  '3000011': '2000001',
  '3000012': '2000002',
  '3000013': '2000003',
}

// ── Pitch color map ─────────────────────────────────────────────────────────

export const pitchColors: Record<string, string> = {
  FB: '#4caf50',
  CB: '#f44336',
  CH: '#ffc107',
  SL: '#2196f3',
  CT: '#9c27b0',
}

// ── Benchmark data for RadarChart ───────────────────────────────────────────

export interface Benchmarks {
  hs: number[]
  college: number[]
  pro: number[]
}

// Hitting benchmarks: [EV, BS, QoC] — normalized 0-100
export const hittingBenchmarks: Benchmarks = {
  hs:      [55, 48, 40],
  college: [72, 65, 62],
  pro:     [90, 82, 85],
}

// Pitching benchmarks: [FBVelo, FBSpin, WC%] — normalized 0-100
export const pitchingBenchmarks: Benchmarks = {
  hs:      [50, 45, 35],
  college: [68, 62, 58],
  pro:     [88, 80, 78],
}

// Strength benchmarks: [JumpHeight, Power, Consistency] — normalized 0-100
export const strengthBenchmarks: Benchmarks = {
  hs:      [45, 40, 42],
  college: [62, 58, 60],
  pro:     [82, 78, 80],
}

// ── Normalize a player stat to 0-100 for radar ─────────────────────────────

export function normalizeHitting(avgEV: number, avgBS: number, _swings: number): number[] {
  // EV: 60-110 → 0-100
  const ev = Math.min(100, Math.max(0, (avgEV - 60) / 50 * 100))
  // BS: 30-70 → 0-100
  const bs = Math.min(100, Math.max(0, (avgBS - 30) / 40 * 100))
  // QoC (quality of contact): based on EV and LA mix
  const qoc = Math.min(100, Math.max(0, ev * 0.6 + bs * 0.4))
  return [+ev.toFixed(0), +bs.toFixed(0), +qoc.toFixed(0)]
}

export function normalizePitching(avgFB: number, spin: number, weakContactPct: number): number[] {
  // FB Velo: 70-100 → 0-100
  const velo = Math.min(100, Math.max(0, (avgFB - 70) / 30 * 100))
  // Spin: 1500-2800 → 0-100
  const sp = Math.min(100, Math.max(0, (spin - 1500) / 1300 * 100))
  // Weak Contact: 0-50 → 0-100
  const wc = Math.min(100, Math.max(0, weakContactPct / 50 * 100))
  return [+velo.toFixed(0), +sp.toFixed(0), +wc.toFixed(0)]
}

// ── Helper to get batter stats with fallback ────────────────────────────────

export function getBatterStats(playerId: string): BatterStats {
  return batterStats[playerId] || batterStats['3000002']
}

export function getPitcherForPlayer(playerId: string): PitcherStats {
  const pitcherId = playerPitcherMap[playerId] || '2000001'
  return pitcherStats[pitcherId] || pitcherStats['2000001']
}

// ── Strength data (not in CSV but needed for demo) ──────────────────────────

export interface StrengthData {
  jumpData: { date: string; value: number }[]
  avgJH: number
  maxJH: number
  lastJump: string
  totalJumps: number
  hsMax: number
  annotations: { date: string; label: string }[]
}

export function getStrengthData(_playerId: string): StrengthData {
  const r = seeded(777)
  const dates = ['9/13', '9/16', '9/25', '10/1', '10/10', '10/13', '10/18', '10/25', '11/1', '11/14', '11/20', '11/24']
  const jumps = dates.map(d => ({ date: d, value: +(8 + r() * 12).toFixed(2) }))
  // Make it trend upward slightly
  jumps.forEach((j, i) => { j.value = +(j.value + i * 0.4).toFixed(2) })
  const vals = jumps.map(j => j.value)
  return {
    jumpData: jumps,
    avgJH: +(vals.reduce((a, b) => a + b, 0) / vals.length).toFixed(2),
    maxJH: +Math.max(...vals).toFixed(2),
    lastJump: '11/24/2025',
    totalJumps: jumps.length,
    hsMax: 25.47,
    annotations: [
      { date: '9/25', label: 'Started new program' },
      { date: '10/18', label: 'Increased weight' },
      { date: '11/14', label: 'PR attempt' },
    ],
  }
}
