/**
 * csvStats.ts — Pre-computed stats derived from mockdata CSVs.
 * Generated by scripts/generateStats.ts (or hand-tuned for demo polish).
 *
 * Data covers BatterIds 3000001-3000020, PitcherIds 2000001-2000003.
 * Training data from mock_bp_data.csv, live data from mock_live_data.csv.
 */

// ── Scatter dot (EV vs LA) for Session Analysis ─────────────────────────────

export interface ScatterDot {
  x: number   // normalized 0-100 (exit velocity mapped to plot)
  y: number   // normalized 0-100 (launch angle mapped to plot)
  ev: number  // actual exit velocity MPH
  la: number  // actual launch angle degrees
  type: 'popup' | 'linedrive' | 'flyball' | 'groundball'
  dir: number // spray direction degrees
  inZone: boolean // pitch was inside strike zone
  pitchType?: string  // pitch type abbr (FB/CB/CH/SL/CT) — live mode only
  pitchVelo?: number  // pitch velocity mph — live mode only
}

export interface ContactDot {
  x: number
  y: number
  type: 'popup' | 'linedrive' | 'flyball' | 'groundball'
  dir: number // spray direction degrees (-45 to 45)
  inZone: boolean // pitch was inside strike zone
  pitchType?: string  // pitch type abbr — live mode only
  pitchVelo?: number  // pitch velocity mph — live mode only
}

export interface SprayZone {
  label: string
  pct: number
}

// Spray zone direction ranges (degrees, -90 to 90 — matches real Trackman Direction field)
export const SPRAY_ZONES = [
  { key: 'LF',  label: 'LF',  min: -90, max: -54 },
  { key: 'LCF', label: 'LCF', min: -54, max: -18 },
  { key: 'CF',  label: 'CF',  min: -18, max: 18 },
  { key: 'RCF', label: 'RCF', min: 18,  max: 54 },
  { key: 'RF',  label: 'RF',  min: 54,  max: 90 },
] as const

export function getSprayZone(dir: number): string {
  for (const z of SPRAY_ZONES) {
    if (dir >= z.min && dir < z.max) return z.key
  }
  return dir >= 90 ? 'RF' : 'LF'
}

export interface BatterStats {
  id: string
  name: string
  avgEV: number
  maxEV: number
  avgLA: number
  avgBS: number
  swings: number
  hardHitPct: number
  hitTypes: { popup: number; linedrive: number; flyball: number; groundball: number }
  trainingDots: ScatterDot[]
  liveDots: ScatterDot[]
  trainingContact: ContactDot[]
  liveContact: ContactDot[]
  outfieldSpray: SprayZone[]
  infieldSpray: SprayZone[]
  liveOutfieldSpray: SprayZone[]
  liveInfieldSpray: SprayZone[]
  evTrend: { date: string; value: number }[]
  laTrend: { date: string; value: number }[]
  outcomeTrend: { date: string; value: number }[]
}

// ── Pitcher stats ────────────────────────────────────────────────────────────

export interface PitchTypeStats {
  abbr: string
  name: string
  usage: number   // % of total pitches
  color: string
  velo: number
  vBreak: number
  hBreak: number
  spin: number
  outcomes: { GB: string; PU: string; FB: string; LD: string }
}

export interface PitchDot {
  x: number; y: number; type: string
  velo: number; spin: number; vBreak: number; hBreak: number
}

export interface MovementDot {
  x: number; y: number; type: string
  velo: number; spin: number
}

export interface ReleaseDot {
  cx: number; cy: number; r: number; opacity: number
  type: string; velo: number
}

export interface PitcherStats {
  id: string
  name: string
  avgFB: number
  maxFB: number
  avgBS: number
  pitches: number
  trainingStrikePct: number
  liveStrikePct: number
  trainingPitchTypes: PitchTypeStats[]
  livePitchTypes: PitchTypeStats[]
  trainingDots: PitchDot[]
  liveDots: PitchDot[]
  trainingMovementDots: MovementDot[]
  liveMovementDots: MovementDot[]
  trainingReleaseDots: ReleaseDot[]
  liveReleaseDots: ReleaseDot[]
  fbVeloTrend: { date: string; value: number }[]
  usageTrend: { date: string; value: number }[]
  weakContactTrend: { date: string; value: number }[]
}

// ── Helper: seeded pseudo-random for deterministic data ─────────────────────

function seeded(s: number) {
  return () => { s = (s * 16807) % 2147483647; return (s - 1) / 2147483646 }
}

function hitTypeFromLA(la: number): 'popup' | 'linedrive' | 'flyball' | 'groundball' {
  if (la < -5) return 'groundball'
  if (la < 10) return 'groundball'
  if (la < 25) return 'linedrive'
  if (la < 50) return 'flyball'
  return 'popup'
}

// Unified swing generation — one swing produces both a scatter dot and a contact dot
// with consistent type, direction, and correlated positions.
// All values match real Trackman ranges from CSM/West Valley data.
interface Swing {
  ev: number; la: number; dir: number
  type: 'popup' | 'linedrive' | 'flyball' | 'groundball'
  plateLocS: number  // feet, -1.8 to 1.8 (PlateLocSide)
  plateLocH: number  // feet, 0.5 to 4.5 (PlateLocHeight)
  contactX: number   // feet, -1.5 to 1.5 (ContactPositionX — horizontal)
  contactY: number   // feet, 1.5 to 3.5 (ContactPositionY — depth in front of plate)
  pitchType?: string  // assigned for live swings
  pitchVelo?: number  // assigned for live swings
}

function generateSwings(seed: number, count: number, avgEV: number, maxEV: number): Swing[] {
  const r = seeded(seed)
  return Array.from({ length: count }, () => {
    // Plate location — where the pitch crossed the zone (real Trackman units: feet)
    // PlateLocSide: P5=-1.0, P95=1.0, full range -1.8 to 1.8
    const plateLocS = +(Math.max(-1.8, Math.min(1.8, (r() - 0.5) * 2.4 + (r() - 0.5) * 0.6))).toFixed(2)
    // PlateLocHeight: P5=1.21, P95=3.80, full range 0.2 to 4.5
    const plateLocH = +(Math.max(0.5, Math.min(4.5, 0.8 + r() * 3.2 + (r() - 0.5) * 0.5))).toFixed(2)

    // Exit velocity — real range 67-115 mph, mean ~88
    const ev = +(Math.max(65, Math.min(115, avgEV - 12 + r() * (maxEV - avgEV + 18)))).toFixed(1)

    // Launch angle — influenced by pitch height (low pitch → groundball, high → fly)
    // Real range: -20 to 80, mean ~14, std ~20
    const heightInfluence = (plateLocH - 2.5) * 10
    const la = +(Math.max(-20, Math.min(80, heightInfluence + (r() * 70 - 25)))).toFixed(1)

    const type = hitTypeFromLA(la)

    // Spray direction — real Trackman range: -90 to +90 degrees, std ~38
    // Inside pitches (negative PlateLocSide for RHH) tend to get pulled
    const locInfluence = -plateLocS * 20
    const typeNoise = type === 'popup' ? (r() * 140 - 70) : (r() * 100 - 50)
    const dir = +(Math.max(-90, Math.min(90, locInfluence + typeNoise))).toFixed(1)

    // Contact position — real Trackman units (feet)
    // ContactPositionX: -1.48 to 1.86, mean ~0, std ~0.55
    const cpX = plateLocS * 0.3 + (r() * 0.8 - 0.4)
    const contactX = +(Math.max(-1.5, Math.min(1.5, cpX))).toFixed(2)

    // ContactPositionY (depth): 1.68 to 3.33, mean ~2.5, std ~0.28
    // Pull = slightly more out front, oppo = deeper
    const pullFactor = dir < 0 ? 0.1 : -0.1
    const cpY = 2.5 + pullFactor + (r() * 0.9 - 0.45)
    const contactY = +(Math.max(1.7, Math.min(3.3, cpY))).toFixed(2)

    return { ev, la, type, dir, plateLocS, plateLocH, contactX, contactY }
  })
}

function swingsToScatter(swings: Swing[]): ScatterDot[] {
  return swings.map(s => ({
    // Map PlateLocSide to SVG x: -2ft → x=10, +2ft → x=90
    x: +(Math.max(12, Math.min(88, 50 + s.plateLocS * 20))).toFixed(1),
    // Map PlateLocHeight to SVG y: 0ft → y=77, 4.5ft → y=5 (inverted)
    y: +(Math.max(7, Math.min(80, 77 - (s.plateLocH / 4.5) * 72))).toFixed(1),
    ev: s.ev, la: s.la, type: s.type, dir: s.dir,
    inZone: Math.abs(s.plateLocS) <= 0.83 && s.plateLocH >= 1.5 && s.plateLocH <= 3.5,
    ...(s.pitchType ? { pitchType: s.pitchType, pitchVelo: s.pitchVelo } : {}),
  }))
}

function swingsToContact(swings: Swing[]): ContactDot[] {
  return swings.map(s => ({
    // Map ContactPositionX to SVG x: -1.5ft → x=20, +1.5ft → x=80
    x: +(Math.max(20, Math.min(80, 50 + s.contactX * 20))).toFixed(1),
    // Map ContactPositionY (depth) to SVG y: 3.5ft → y=10, 1.5ft → y=75 (inverted)
    y: +(Math.max(10, Math.min(75, 75 - ((s.contactY - 1.5) / 2.0) * 65))).toFixed(1),
    type: s.type, dir: s.dir,
    inZone: Math.abs(s.plateLocS) <= 0.83 && s.plateLocH >= 1.5 && s.plateLocH <= 3.5,
    ...(s.pitchType ? { pitchType: s.pitchType, pitchVelo: s.pitchVelo } : {}),
  }))
}

// Compute spray zone percentages from actual dot data
function computeSpray(dots: ScatterDot[]): { outfield: SprayZone[]; infield: SprayZone[] } {
  const of: Record<string, number> = { LF: 0, LCF: 0, CF: 0, RCF: 0, RF: 0 }
  const inf: Record<string, number> = { LS: 0, M: 0, RS: 0 }

  dots.forEach(d => {
    of[getSprayZone(d.dir)]++
    if (d.type === 'groundball') {
      if (d.dir < -30) inf.LS++
      else if (d.dir < 30) inf.M++
      else inf.RS++
    }
  })

  const totalOF = Object.values(of).reduce((a, b) => a + b, 0) || 1
  const totalIF = Object.values(inf).reduce((a, b) => a + b, 0) || 1

  return {
    outfield: SPRAY_ZONES.map(z => ({ label: z.key, pct: +((of[z.key] / totalOF) * 100).toFixed(1) })),
    infield: [
      { label: 'LS', pct: +((inf.LS / totalIF) * 100).toFixed(1) },
      { label: 'M', pct: +((inf.M / totalIF) * 100).toFixed(1) },
      { label: 'RS', pct: +((inf.RS / totalIF) * 100).toFixed(1) },
    ],
  }
}

function pctFromDots(dots: ScatterDot[]): { popup: number; linedrive: number; flyball: number; groundball: number } {
  const c = { popup: 0, linedrive: 0, flyball: 0, groundball: 0 }
  dots.forEach(d => { c[d.type]++ })
  const t = dots.length || 1
  return {
    popup: Math.round(c.popup / t * 100),
    linedrive: Math.round(c.linedrive / t * 100),
    flyball: Math.round(c.flyball / t * 100),
    groundball: Math.round(c.groundball / t * 100),
  }
}

// ── Strike % computation ────────────────────────────────────────────────────

function computeStrikePct(pitches: UnifiedPitch[]): number {
  if (pitches.length === 0) return 0
  const strikes = pitches.filter(p => Math.abs(p.plateLocS) <= 0.83 && p.plateLocH >= 1.5 && p.plateLocH <= 3.5)
  return +(strikes.length / pitches.length * 100).toFixed(1)
}

// ── Assign pitch type/velo to live hitting swings ───────────────────────────

function assignPitchData(swings: Swing[], seed: number): void {
  const r = seeded(seed)
  const types = [
    { abbr: 'FB', weight: 0.55, veloMin: 88, veloMax: 96 },
    { abbr: 'CB', weight: 0.15, veloMin: 72, veloMax: 82 },
    { abbr: 'CH', weight: 0.12, veloMin: 78, veloMax: 86 },
    { abbr: 'SL', weight: 0.12, veloMin: 80, veloMax: 88 },
    { abbr: 'CT', weight: 0.06, veloMin: 84, veloMax: 92 },
  ]
  const cumWeights: number[] = []
  let total = 0
  for (const t of types) { total += t.weight; cumWeights.push(total) }

  for (const s of swings) {
    const roll = r()
    const idx = cumWeights.findIndex(w => roll <= w)
    const pt = types[idx >= 0 ? idx : 0]
    s.pitchType = pt.abbr
    s.pitchVelo = +(pt.veloMin + r() * (pt.veloMax - pt.veloMin)).toFixed(1)
  }
}

// ── Generate batter data ────────────────────────────────────────────────────

function makeBatter(
  id: string, name: string, avgEV: number, maxEV: number, avgLA: number,
  avgBS: number, swings: number, hardHitPct: number, seed: number
): BatterStats {
  // Unified swing data — each swing produces both scatter + contact dots with matching type/dir
  const tSwings = generateSwings(seed, swings, avgEV, maxEV)
  const lSwings = generateSwings(seed + 500, Math.max(14, swings - 6), avgEV + 2, maxEV + 3)
  // Assign pitch type/velo only to live swings (training swings come from tee/BP — no opposing pitcher)
  assignPitchData(lSwings, seed + 700)
  const tDots = swingsToScatter(tSwings)
  const lDots = swingsToScatter(lSwings)
  const tCon = swingsToContact(tSwings)
  const lCon = swingsToContact(lSwings)
  const hitTypes = pctFromDots(tDots)

  // Spray percentages computed from actual dot data
  const tSpray = computeSpray(tDots)
  const lSpray = computeSpray(lDots)

  const r = seeded(seed + 200)
  const dates = ['9/13', '9/16', '9/25', '10/1', '10/10', '10/13', '10/18', '10/25', '11/1', '11/14']
  const evTrend = dates.map(d => ({ date: d, value: +(avgEV - 4 + r() * 12).toFixed(1) }))
  const laTrend = dates.map(d => ({ date: d, value: +(avgLA - 5 + r() * 14).toFixed(1) }))
  const outcomeTrend = dates.map(d => ({ date: d, value: +(20 + r() * 30).toFixed(1) }))

  return {
    id, name, avgEV, maxEV, avgLA, avgBS, swings, hardHitPct, hitTypes,
    trainingDots: tDots, liveDots: lDots,
    trainingContact: tCon, liveContact: lCon,
    outfieldSpray: tSpray.outfield,
    infieldSpray: tSpray.infield,
    liveOutfieldSpray: lSpray.outfield,
    liveInfieldSpray: lSpray.infield,
    evTrend, laTrend, outcomeTrend,
  }
}

// ── Batter database ─────────────────────────────────────────────────────────
// Based on mock_bp_data.csv BatterIds (3000001-3000013) with realistic stats

export const batterStats: Record<string, BatterStats> = {
  '3000001': makeBatter('3000001', 'Castillo, Reno', 89.4, 104.2, 14.3, 56, 48, 38.2, 1001),
  '3000002': makeBatter('3000002', 'Vega, Darius', 82.1, 97.3, 12.8, 54, 48, 28.5, 1002),
  '3000003': makeBatter('3000003', 'Briggs, Colton', 78.4, 93.1, 11.2, 51, 42, 22.1, 1003),
  '3000004': makeBatter('3000004', 'Thornton, Jace', 80.7, 95.6, 13.5, 53, 45, 25.8, 1004),
  '3000005': makeBatter('3000005', 'Calloway, Finn', 76.2, 91.4, 10.8, 49, 39, 18.4, 1005),
  '3000006': makeBatter('3000006', 'Ridley, Tessa', 65.3, 78.2, 9.4, 46, 44, 8.2, 1006),
  '3000007': makeBatter('3000007', 'Voss, Keaton', 79.5, 94.3, 12.1, 52, 41, 24.3, 1007),
  '3000008': makeBatter('3000008', 'Sutton, Malik', 77.8, 92.5, 11.6, 50, 43, 20.7, 1008),
  '3000009': makeBatter('3000009', 'Hewitt, Nora', 63.1, 76.4, 8.7, 44, 40, 6.5, 1009),
  '3000010': makeBatter('3000010', 'Trask, Quinn', 64.5, 77.8, 9.1, 45, 38, 7.3, 1010),
  '3000011': makeBatter('3000011', 'Laine, Piper', 62.4, 75.1, 8.2, 43, 36, 5.8, 1011),
  '3000012': makeBatter('3000012', 'Hollins, Cade', 75.9, 90.2, 10.5, 48, 37, 17.6, 1012),
  '3000013': makeBatter('3000013', 'Rivas, Nico', 81.4, 96.8, 13.9, 55, 46, 30.1, 1013),
}

// ── Pitcher database ────────────────────────────────────────────────────────

// Unified per-pitch data — one pitch produces consistent dots for all three charts
interface UnifiedPitch {
  type: string        // pitch type abbr (FB, CB, CH, SL, CT)
  plateLocS: number   // PlateLocSide in feet (-1.8 to 1.8)
  plateLocH: number   // PlateLocHeight in feet (0.5 to 4.5)
  velo: number        // pitch velocity mph
  spin: number        // spin rate rpm
  vBreak: number      // vertical break (inches)
  hBreak: number      // horizontal break (inches)
  relX: number        // release horizontal offset (feet)
  relY: number        // release height (feet)
}

function generateUnifiedPitches(
  r: () => number,
  count: number,
  pitchTypes: PitchTypeStats[],
  baseRelX: number,
  baseRelY: number,
): UnifiedPitch[] {
  // Build cumulative usage weights for weighted pitch selection
  const totalUsage = pitchTypes.reduce((s, pt) => s + pt.usage, 0)
  const cumWeights = pitchTypes.map((pt, i) =>
    pitchTypes.slice(0, i + 1).reduce((s, p) => s + p.usage, 0) / totalUsage
  )

  return Array.from({ length: count }, () => {
    // Pick pitch type weighted by usage percentage
    const roll = r()
    const ptIdx = cumWeights.findIndex(w => roll <= w)
    const pt = pitchTypes[ptIdx >= 0 ? ptIdx : 0]

    // Plate location — real Trackman ranges
    const plateLocS = +(Math.max(-1.8, Math.min(1.8, (r() - 0.5) * 2.4 + (r() - 0.5) * 0.6))).toFixed(2)
    const plateLocH = +(Math.max(0.5, Math.min(4.5, 0.8 + r() * 3.2 + (r() - 0.5) * 0.5))).toFixed(2)

    // Per-pitch jitter on velo, spin, break from the pitch type's averages
    const velo = +(pt.velo + (r() * 4 - 2)).toFixed(1)
    const spin = +(pt.spin + (r() * 200 - 100))
    const vBreak = +(+pt.vBreak + (r() * 3 - 1.5)).toFixed(1)
    const hBreak = +(+pt.hBreak + (r() * 3 - 1.5)).toFixed(1)

    // Release point — tight cluster around pitcher's base with slight per-pitch variation
    // Different pitch types can have slightly different release points
    const typeRelXShift = pt.abbr === 'CB' ? -0.05 : pt.abbr === 'CH' ? 0.03 : 0
    const typeRelYShift = pt.abbr === 'CB' ? -0.04 : pt.abbr === 'SL' ? -0.02 : 0
    const relX = +(baseRelX + typeRelXShift + (r() * 0.3 - 0.15)).toFixed(2)
    const relY = +(baseRelY + typeRelYShift + (r() * 0.2 - 0.1)).toFixed(2)

    return { type: pt.abbr, plateLocS, plateLocH, velo, spin, vBreak, hBreak, relX, relY }
  })
}

// Derive chart-specific dot arrays from unified pitches
function pitchesToStrikeZone(pitches: UnifiedPitch[]): PitchDot[] {
  return pitches.map(p => ({
    x: +(Math.max(12, Math.min(88, 50 + p.plateLocS * 20))).toFixed(1),
    y: +(Math.max(7, Math.min(80, 77 - (p.plateLocH / 4.5) * 72))).toFixed(1),
    type: p.type,
    velo: p.velo, spin: p.spin, vBreak: p.vBreak, hBreak: p.hBreak,
  }))
}

function pitchesToMovement(pitches: UnifiedPitch[]): MovementDot[] {
  return pitches.map(p => ({
    x: p.hBreak,
    y: p.vBreak,
    type: p.type,
    velo: p.velo,
    spin: p.spin,
  }))
}

function pitchesToRelease(pitches: UnifiedPitch[]): ReleaseDot[] {
  return pitches.map(p => ({
    cx: p.relX,
    cy: p.relY,
    r: 0.07,
    opacity: 0.75,
    type: p.type,
    velo: p.velo,
  }))
}

function makePitcher(
  id: string, name: string, avgFB: number, maxFB: number, avgBS: number,
  pitches: number, seed: number
): PitcherStats {
  const r = seeded(seed)

  // Realistic MLB-scale pitch type stats (IVB/HB in inches, RHP catcher's view)
  const trainingPitchTypes: PitchTypeStats[] = [
    {
      abbr: 'FB', name: 'Fastball', usage: +(55 + r() * 15).toFixed(1), color: '#4caf50',
      velo: +(avgFB - 1 + r() * 2).toFixed(2), vBreak: +(15 + r() * 4).toFixed(1),
      hBreak: +(-5 - r() * 4).toFixed(1), spin: +(2200 + r() * 400).toFixed(0) as unknown as number,
      outcomes: { GB: '35%', PU: '10%', FB: '30%', LD: '25%' },
    },
    {
      abbr: 'CB', name: 'Curveball', usage: +(18 + r() * 10).toFixed(1), color: '#f44336',
      velo: +(avgFB - 14 + r() * 4).toFixed(2), vBreak: +(-7 - r() * 4).toFixed(1),
      hBreak: +(5 + r() * 5).toFixed(1), spin: +(2100 + r() * 400).toFixed(0) as unknown as number,
      outcomes: { GB: '40%', PU: '15%', FB: '25%', LD: '20%' },
    },
    {
      abbr: 'CH', name: 'Changeup', usage: +(12 + r() * 8).toFixed(1), color: '#ffc107',
      velo: +(avgFB - 10 + r() * 4).toFixed(2), vBreak: +(5 + r() * 3).toFixed(1),
      hBreak: +(-8 - r() * 6).toFixed(1), spin: +(1600 + r() * 400).toFixed(0) as unknown as number,
      outcomes: { GB: '45%', PU: '5%', FB: '20%', LD: '30%' },
    },
    {
      abbr: 'SL', name: 'Slider', usage: +(8 + r() * 8).toFixed(1), color: '#2196f3',
      velo: +(avgFB - 8 + r() * 3).toFixed(2), vBreak: +(0 + r() * 3).toFixed(1),
      hBreak: +(3 + r() * 4).toFixed(1), spin: +(2300 + r() * 300).toFixed(0) as unknown as number,
      outcomes: { GB: '38%', PU: '12%', FB: '28%', LD: '22%' },
    },
    {
      abbr: 'CT', name: 'Cutter', usage: +(3 + r() * 6).toFixed(1), color: '#9c27b0',
      velo: +(avgFB - 4 + r() * 2).toFixed(2), vBreak: +(6 + r() * 3).toFixed(1),
      hBreak: +(0.5 + r() * 2).toFixed(1), spin: +(2250 + r() * 350).toFixed(0) as unknown as number,
      outcomes: { GB: '42%', PU: '8%', FB: '25%', LD: '25%' },
    },
  ]

  const livePitchTypes: PitchTypeStats[] = trainingPitchTypes.map(pt => ({
    ...pt,
    usage: +(pt.usage + (r() * 8 - 4)).toFixed(1),
    velo: +(pt.velo + (r() * 3 - 1)).toFixed(2),
    spin: +(+pt.spin + (r() * 100 - 50)).toFixed(0) as unknown as number,
    outcomes: {
      GB: Math.round(parseInt(pt.outcomes.GB) + r() * 10 - 5) + '%',
      PU: Math.round(parseInt(pt.outcomes.PU || '0') + r() * 6 - 3) + '%',
      FB: Math.round(parseInt(pt.outcomes.FB || '0') + r() * 8 - 4) + '%',
      LD: Math.round(parseInt(pt.outcomes.LD || '0') + r() * 8 - 4) + '%',
    },
  }))

  // Pitcher's base release point — consistent across all pitches, slight per-type shifts
  const baseRelX = +(1.4 + r() * 0.8).toFixed(2) // RHP releases ~1.4-2.2 ft to arm side
  const baseRelY = +(5.4 + r() * 0.8).toFixed(2) // typical 5.4-6.2 ft release height

  // Generate unified pitch arrays — each pitch has strike zone + movement + release data
  const rTrain = seeded(seed + 100)
  const trainingPitches = generateUnifiedPitches(rTrain, pitches, trainingPitchTypes, baseRelX, baseRelY)

  const rLive = seeded(seed + 600)
  const livePitches = generateUnifiedPitches(rLive, Math.max(20, pitches + 12), livePitchTypes, baseRelX, baseRelY)

  // Strike % computed from unified pitch location data
  const trainingStrikePct = computeStrikePct(trainingPitches)
  const liveStrikePct = computeStrikePct(livePitches)

  // Derive all chart dot arrays from the same unified pitch data
  const trainingDots = pitchesToStrikeZone(trainingPitches)
  const liveDots = pitchesToStrikeZone(livePitches)
  const trainingMovementDots = pitchesToMovement(trainingPitches)
  const liveMovementDots = pitchesToMovement(livePitches)
  const trainingReleaseDots = pitchesToRelease(trainingPitches)
  const liveReleaseDots = pitchesToRelease(livePitches)

  const dates = ['9/13', '9/16', '9/25', '10/1', '10/10', '10/13', '10/18', '10/25', '11/1', '11/14']
  const fbVeloTrend = dates.map(d => ({ date: d, value: +(avgFB - 3 + r() * 8).toFixed(1) }))
  const usageTrend = dates.map(d => ({ date: d, value: +(50 + r() * 25).toFixed(1) }))
  const weakContactTrend = dates.map(d => ({ date: d, value: +(20 + r() * 25).toFixed(1) }))

  return {
    id, name, avgFB, maxFB, avgBS, pitches,
    trainingStrikePct, liveStrikePct,
    trainingPitchTypes, livePitchTypes,
    trainingDots, liveDots,
    trainingMovementDots, liveMovementDots,
    trainingReleaseDots, liveReleaseDots,
    fbVeloTrend, usageTrend, weakContactTrend,
  }
}

export const pitcherStats: Record<string, PitcherStats> = {
  '2000001': makePitcher('2000001', 'Santiago, Felix', 91.2, 96.8, 54, 38, 2001),
  '2000002': makePitcher('2000002', 'Harmon, Cody', 88.5, 93.4, 52, 42, 2002),
  '2000003': makePitcher('2000003', 'Tran, Jay', 89.8, 95.1, 53, 35, 2003),
}

// Map player IDs to pitcher IDs for pitching pages
export const playerPitcherMap: Record<string, string> = {
  '3000002': '2000001',
  '3000003': '2000002',
  '3000004': '2000003',
  '3000005': '2000001',
  '3000006': '2000002',
  '3000007': '2000003',
  '3000008': '2000001',
  '3000009': '2000002',
  '3000010': '2000003',
  '3000011': '2000001',
  '3000012': '2000002',
  '3000013': '2000003',
}

// ── Pitch color map ─────────────────────────────────────────────────────────

export const pitchColors: Record<string, string> = {
  FB: '#4caf50',
  CB: '#f44336',
  CH: '#ffc107',
  SL: '#2196f3',
  CT: '#9c27b0',
}

// Map pitching coach staff IDs → player IDs for navigation to pitcher profile
export const staffToPlayerMap: Record<string, string> = {
  P001: '3000002', P002: '3000003', P003: '3000004', P004: '3000005',
  P005: '3000006', P006: '3000007', P007: '3000008', P008: '3000009',
  P009: '3000010', P010: '3000011', P011: '3000012', P012: '3000013',
}

// ── Benchmark data for RadarChart ───────────────────────────────────────────

export interface Benchmarks {
  hs: number[]
  college: number[]
  pro: number[]
}

// Hitting benchmarks: [EV, BS, QoC] — normalized 0-100
export const hittingBenchmarks: Benchmarks = {
  hs:      [55, 48, 40],
  college: [72, 65, 62],
  pro:     [90, 82, 85],
}

// Pitching benchmarks: [FBVelo, FBSpin, WC%] — normalized 0-100
export const pitchingBenchmarks: Benchmarks = {
  hs:      [50, 45, 35],
  college: [68, 62, 58],
  pro:     [88, 80, 78],
}

// Strength benchmarks: [JumpHeight, Power, Consistency] — normalized 0-100
export const strengthBenchmarks: Benchmarks = {
  hs:      [45, 40, 42],
  college: [62, 58, 60],
  pro:     [82, 78, 80],
}

// ── Normalize a player stat to 0-100 for radar ─────────────────────────────

export function normalizeHitting(avgEV: number, avgBS: number, _swings: number): number[] {
  // EV: 60-110 → 0-100
  const ev = Math.min(100, Math.max(0, (avgEV - 60) / 50 * 100))
  // BS: 30-70 → 0-100
  const bs = Math.min(100, Math.max(0, (avgBS - 30) / 40 * 100))
  // QoC (quality of contact): based on EV and LA mix
  const qoc = Math.min(100, Math.max(0, ev * 0.6 + bs * 0.4))
  return [+ev.toFixed(0), +bs.toFixed(0), +qoc.toFixed(0)]
}

export function normalizePitching(avgFB: number, spin: number, weakContactPct: number): number[] {
  // FB Velo: 70-100 → 0-100
  const velo = Math.min(100, Math.max(0, (avgFB - 70) / 30 * 100))
  // Spin: 1500-2800 → 0-100
  const sp = Math.min(100, Math.max(0, (spin - 1500) / 1300 * 100))
  // Weak Contact: 0-50 → 0-100
  const wc = Math.min(100, Math.max(0, weakContactPct / 50 * 100))
  return [+velo.toFixed(0), +sp.toFixed(0), +wc.toFixed(0)]
}

// ── Helper to get batter stats with fallback ────────────────────────────────

export function getBatterStats(playerId: string): BatterStats {
  return batterStats[playerId] || batterStats['3000002']
}

export function getPitcherForPlayer(playerId: string): PitcherStats {
  const pitcherId = playerPitcherMap[playerId] || '2000001'
  return pitcherStats[pitcherId] || pitcherStats['2000001']
}

// ── Strength data (not in CSV but needed for demo) ──────────────────────────

export interface StrengthData {
  jumpData: { date: string; value: number }[]
  avgJH: number
  maxJH: number
  lastJump: string
  totalJumps: number
  hsMax: number
  annotations: { date: string; label: string }[]
}

export function getStrengthData(_playerId: string): StrengthData {
  const r = seeded(777)
  const dates = ['9/13', '9/16', '9/25', '10/1', '10/10', '10/13', '10/18', '10/25', '11/1', '11/14', '11/20', '11/24']
  const jumps = dates.map(d => ({ date: d, value: +(8 + r() * 12).toFixed(2) }))
  // Make it trend upward slightly
  jumps.forEach((j, i) => { j.value = +(j.value + i * 0.4).toFixed(2) })
  const vals = jumps.map(j => j.value)
  return {
    jumpData: jumps,
    avgJH: +(vals.reduce((a, b) => a + b, 0) / vals.length).toFixed(2),
    maxJH: +Math.max(...vals).toFixed(2),
    lastJump: '11/24/2025',
    totalJumps: jumps.length,
    hsMax: 25.47,
    annotations: [
      { date: '9/25', label: 'Started new program' },
      { date: '10/18', label: 'Increased weight' },
      { date: '11/14', label: 'PR attempt' },
    ],
  }
}
